fix(kafka): fix kafka not running

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -47,7 +47,14 @@ services:
       KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9997
     volumes:
       - ./update_run.sh:/tmp/update_run.sh
-    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
+    command: 
+      - bash 
+      - -c
+      - |
+        if [ ! -f /tmp/update_run.sh ]; 
+        then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; 
+        else chmod +x /tmp/update_run.sh && /tmp/update_run.sh && /etc/confluent/docker/run ; 
+        fi
 
   schema-registry:
     image: confluentinc/cp-schema-registry:7.2.1.arm64
